#pragma once

#ifdef RGB_MATRIX_ENABLE
#  define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#  define RGB_DISABLE_TIMEOUT 1200000 // 20 minutes (20 * 60 * 1000ms)
#  define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif // RGB_MATRIX_ENABLE
